// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMUJnBaS4wRGKHgqxJIg8nItgmgDtr_E',
    appId: '1:820853000577:web:de835e26caa507d089c080',
    messagingSenderId: '820853000577',
    projectId: 'onelife-2e488',
    authDomain: 'onelife-2e488.firebaseapp.com',
    storageBucket: 'onelife-2e488.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWCLWFDH1DXcz3U9a-aPwYpAqbOuFhMk',
    appId: '1:820853000577:android:e97de81d381a2adf89c080',
    messagingSenderId: '820853000577',
    projectId: 'onelife-2e488',
    storageBucket: 'onelife-2e488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnxdCoTBL13Pm_7uooK0qS-H8kvkfUO2s',
    appId: '1:820853000577:ios:db2a6975afbc5e4f89c080',
    messagingSenderId: '820853000577',
    projectId: 'onelife-2e488',
    storageBucket: 'onelife-2e488.firebasestorage.app',
    iosBundleId: 'com.example.onelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnxdCoTBL13Pm_7uooK0qS-H8kvkfUO2s',
    appId: '1:820853000577:ios:db2a6975afbc5e4f89c080',
    messagingSenderId: '820853000577',
    projectId: 'onelife-2e488',
    storageBucket: 'onelife-2e488.firebasestorage.app',
    iosBundleId: 'com.example.onelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlMUJnBaS4wRGKHgqxJIg8nItgmgDtr_E',
    appId: '1:820853000577:web:a6c1be36f8190a9b89c080',
    messagingSenderId: '820853000577',
    projectId: 'onelife-2e488',
    authDomain: 'onelife-2e488.firebaseapp.com',
    storageBucket: 'onelife-2e488.firebasestorage.app',
  );
}
